CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    Username VARCHAR(32) NOT NULL UNIQUE,
    Email VARCHAR(32) NOT NULL UNIQUE,
    PhoneNumber VARCHAR(16) NOT NULL UNIQUE,
	UserPassword VARCHAR(32) NOT NULL,
    FirstName NVARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	MiddleName NVARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	LastName NVARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	Bio NVARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    Avatar VARCHAR(255) NOT NULL,
    LastLogin DATETIME2(6) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Conversations(
	ConversationID INT PRIMARY KEY IDENTITY(1,1),
	ConversationName VARCHAR(32) UNIQUE,
	ConversationTitle VARCHAR(32) COLLATE SQL_Latin1_General_CP1_CI_AS,
	CreatorID INT NOT NULL,
	CorversationType VARCHAR(7) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT SYSDATETIME(),
	Deleted BIT DEFAULT 0,
	FOREIGN KEY (CreatorID) REFERENCES Users(UserID)
)

CREATE TABLE Messages(
	 MessageID INT PRIMARY KEY IDENTITY(1,1),
	 ConversationID INT NOT NULL,
	 SenderID INT NOT NULL,
	 Content VARCHAR(MAX) NOT NULL,
	 MessageType VARCHAR(5) NOT NULL,
	 Attachment BIT NOT NULL,
	 Deleted BIT NOT NULL,
	 Timestamp DATETIME NOT NULL DEFAULT SYSDATETIME()
	 FOREIGN KEY (ConversationID) REFERENCES Conversations(ConversationID),
	 FOREIGN KEY (SenderID) REFERENCES Users(UserID)
)

CREATE TABLE Participants(
	ParticipantID INT PRIMARY KEY IDENTITY(1,1),
	ConversationID INT NOT NULL,
	UserID INT NOT NULL,
	FOREIGN KEY (ConversationID) REFERENCES Conversations(ConversationID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
)

CREATE TABLE Attachments(
	AttachmentID INT PRIMARY KEY IDENTITY(1,1), 
	MessageID INT NOT NULL,
	AttachmentsType VARCHAR(5) NOT NULL,
	ThumbnailURL VARCHAR(128) NOT NULL,
	FileURL VARCHAR(128) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT SYSDATETIME(),
	DeleteDate DATETIME
	FOREIGN KEY (MessageID) REFERENCES Messages(MessageID),
)

CREATE TABLE DeletedConversations(
	DeletedConversationID INT PRIMARY KEY IDENTITY(1,1),
	ConversationID INT NOT NULL,
	UserID INT NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT SYSDATETIME(),
	FOREIGN KEY (ConversationID) REFERENCES Conversations(ConversationID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
)