CREATE TABLE Users (
	UserID INT PRIMARY KEY IDENTITY(1,1),
    Username VARCHAR(32) NOT NULL UNIQUE,
	Password_Hash VARCHAR(60) NOT NULL,
);

CREATE TABLE Messages(
	 MessageID INT PRIMARY KEY IDENTITY(1,1),
	 SenderID INT NOT NULL,
	 ReceiverID INT NOT NULL,
	 Content VARCHAR(MAX) NULL,
	 Message_Type VARCHAR(8) NOT NULL,
	 Created_At DATETIME2(3) NOT NULL DEFAULT SYSDATETIME(),
	 FOREIGN KEY (SenderID) REFERENCES Users(UserID),
	 FOREIGN KEY (ReceiverID) REFERENCES Users(UserID)
);